networks:
  mgmt:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-13
    ipam:
      config:
      - subnet: 192.168.18.0/24
        gateway: 192.168.18.100
  xrd-1-gi2-xrd-2-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-0
    internal: true
    name: xrd-1-gi2-xrd-2-gi2
  xrd-2-gi0-xrd-3-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-1
    internal: true
    name: xrd-2-gi0-xrd-3-gi0
  xrd-2-gi1-xrd-6-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-2
    internal: true
    name: xrd-2-gi1-xrd-6-gi1
  xrd-2-gi3-xrd-7-gi3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-3
    internal: true
    name: xrd-2-gi3-xrd-7-gi3
  xrd-2-gi5-xrd-9-gi5:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-4
    internal: true
    name: xrd-2-gi5-xrd-9-gi5
  xrd-3-gi1-xrd-7-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-5
    internal: true
    name: xrd-3-gi1-xrd-7-gi1
  xrd-3-gi2-xrd-4-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-6
    internal: true
    name: xrd-3-gi2-xrd-4-gi2
  xrd-3-gi3-xrd-9-gi3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-7
    internal: true
    name: xrd-3-gi3-xrd-9-gi3
  xrd-4-gi0-xrd-5-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-8
    internal: true
    name: xrd-4-gi0-xrd-5-gi0
  xrd-4-gi1-xrd-8-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-9
    internal: true
    name: xrd-4-gi1-xrd-8-gi1
  xrd-4-gi4-xrd-7-gi4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-10
    internal: true
    name: xrd-4-gi4-xrd-7-gi4
  xrd-6-gi0-xrd-7-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-11
    internal: true
    name: xrd-6-gi0-xrd-7-gi0
  xrd-7-gi2-xrd-8-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-12
    internal: true
    name: xrd-7-gi2-xrd-8-gi2
services:
  xrd-1:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-1
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-00,xr_name=Gi0/0/0/2
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-1-gi2-xrd-2-gi2: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-1-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-1:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-2:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-2
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-10,xr_name=Gi0/0/0/0;linux:xr-20,xr_name=Gi0/0/0/1;linux:xr-00,xr_name=Gi0/0/0/2;linux:xr-30,xr_name=Gi0/0/0/3;linux:xr-40,xr_name=Gi0/0/0/5
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-1-gi2-xrd-2-gi2: null
      xrd-2-gi0-xrd-3-gi0: null
      xrd-2-gi1-xrd-6-gi1: null
      xrd-2-gi3-xrd-7-gi3: null
      xrd-2-gi5-xrd-9-gi5: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-2-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-2:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-3:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-3
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-10,xr_name=Gi0/0/0/0;linux:xr-50,xr_name=Gi0/0/0/1;linux:xr-60,xr_name=Gi0/0/0/2;linux:xr-70,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-2-gi0-xrd-3-gi0: null
      xrd-3-gi1-xrd-7-gi1: null
      xrd-3-gi2-xrd-4-gi2: null
      xrd-3-gi3-xrd-9-gi3: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-3-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-3:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-4:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-4
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-80,xr_name=Gi0/0/0/0;linux:xr-90,xr_name=Gi0/0/0/1;linux:xr-60,xr_name=Gi0/0/0/2;linux:xr-100,xr_name=Gi0/0/0/4
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-3-gi2-xrd-4-gi2: null
      xrd-4-gi0-xrd-5-gi0: null
      xrd-4-gi1-xrd-8-gi1: null
      xrd-4-gi4-xrd-7-gi4: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-4-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-4:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-5:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-5
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-80,xr_name=Gi0/0/0/0
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-4-gi0-xrd-5-gi0: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-5-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-5:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-6:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-6
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-110,xr_name=Gi0/0/0/0;linux:xr-20,xr_name=Gi0/0/0/1
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-2-gi1-xrd-6-gi1: null
      xrd-6-gi0-xrd-7-gi0: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-6-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-6:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-7:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-7
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-110,xr_name=Gi0/0/0/0;linux:xr-50,xr_name=Gi0/0/0/1;linux:xr-120,xr_name=Gi0/0/0/2;linux:xr-30,xr_name=Gi0/0/0/3;linux:xr-100,xr_name=Gi0/0/0/4
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-2-gi3-xrd-7-gi3: null
      xrd-3-gi1-xrd-7-gi1: null
      xrd-4-gi4-xrd-7-gi4: null
      xrd-6-gi0-xrd-7-gi0: null
      xrd-7-gi2-xrd-8-gi2: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-7-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-7:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-8:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-8
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-90,xr_name=Gi0/0/0/1;linux:xr-120,xr_name=Gi0/0/0/2
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-4-gi1-xrd-8-gi1: null
      xrd-7-gi2-xrd-8-gi2: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-8-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-8:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
  xrd-9:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-9
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-70,xr_name=Gi0/0/0/3;linux:xr-40,xr_name=Gi0/0/0/5
      XR_MGMT_INTERFACES: linux:xr-130,xr_name=Mg0/RP0/CPU0/0,chksum
    image: localhost/ios-xr:7.7.1
    networks:
      mgmt: null
      xrd-2-gi5-xrd-9-gi5: null
      xrd-3-gi3-xrd-9-gi3: null
    security_opt:
    - apparmor:unconfined
    - label:disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-9-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-9:/xr-storage/
    - read_only: true
      source: /sys/fs/cgroup
      target: /sys/fs/cgroup
      type: bind
version: '2.4'
volumes:
  xrd-1:
    name: xrd-1
  xrd-2:
    name: xrd-2
  xrd-3:
    name: xrd-3
  xrd-4:
    name: xrd-4
  xrd-5:
    name: xrd-5
  xrd-6:
    name: xrd-6
  xrd-7:
    name: xrd-7
  xrd-8:
    name: xrd-8
  xrd-9:
    name: xrd-9
