---
- name: "0. RESTORE BASE TOPOLOGY"
  hosts: routers
  gather_facts: false
  vars:
    #The default ssh_type ansible-pylibssh has a bug while replacing config
    ansible_network_cli_ssh_type: paramiko
    slow_secs: 1
    templates:
    - restore_topology_template.j2
  tasks:
  - name: 0.0 RENDER AND DISPLAY THE BASE CONFIGURATION
    debug:
      msg: 
      - "template: {{ templates[0] }}"
      - "{{ lookup('template', templates[0]).split('\n') }}"

  - name: 0.1 RENDER AND SAVE THE BASE CONFIGURATION
    template:
      src: "{{ templates[0] }}"
      dest: "xrcfg/{{ hostname }}.base.xrcfg"
    register: output

  - name: "{{ slow_secs }} secs PAUSE FOR CONVERGENCE"
    ansible.builtin.pause:
      seconds: "{{ slow_secs }}"

  - name: 0.2 DISPLAY THE OUTPUT REGISTERED IN THE PREVIOUS TASK
    debug:
      var: output.dest

  - name: 0.3 RENDER AND APPLY THE BASE CONFIGURATION
    cisco.iosxr.iosxr_config:
      src: "{{ templates[0] }}"
      replace: config
