---
- name: "4. CISCO XRV9K SR WITH TI-LFA LAB PLAYBOOK - TOPOLOGY INDEPENDENT LOOPFREE ALTERNATE"
  hosts: routers !P9
  gather_facts: false
  vars:
    mins: 1
    slow_secs: 1
    templates:
    - tilfa.j2
    command_set_1:
    - show isis interface GigabitEthernet 0/0/0/0
    - show isis fast-reroute 5.5.5.5/32 detail
    - show route 5.5.5.5/32
    - show cef 5.5.5.5/32
  tasks:
  - name: 4.0 RENDER AND DISPLAY THE TI-LFA CONFIGURATION
    debug:
      msg:
      - "template: {{ templates[0] }}"
      - "{{ lookup('template', templates[0]).split('\n') }}"

  - name: 4.1 RENDER AND SAVE THE TI-LFA CONFIGURATION
    template:
      src: "{{ templates[0] }}"
      dest: "xrcfg/{{ hostname }}.tilfa.xrcfg"
    register: output

  - name: "{{ slow_secs }} secs PAUSE FOR CONVERGENCE"
    ansible.builtin.pause:
      seconds: "{{ slow_secs }}"

  - name: 4.2 DISPLAY THE OUTPUT REGISTERED IN THE PREVIOUS TASK
    debug:
      var: output.dest

  - name: 4.3 RENDER AND APPLY THE TI-LFA CONFIGURATION
    cisco.iosxr.iosxr_config:
      src: "{{ templates[0] }}"
      match: none

  - name: "{{ mins }} minutes PAUSE FOR CONVERGENCE"
    ansible.builtin.pause:
      minutes: "{{ mins }}"

  - name: 4.4 RUN COMMANDS TO VERIFY TI-LFA IS ENABLED
    cisco.iosxr.iosxr_command:
      commands:
      - "{{ item }}"
    loop: "{{ command_set_1 }}"
    when: hostname == "P2"
    register: output

  - name: 4.5 DISPLAY THE OUTPUT REGISTERED IN THE PREVIOUS TASK
    debug:
      msg:
      - "{{ output.results[idx].stdout_lines }}"
    loop: "{{ command_set_1 }}"
    loop_control:
      index_var: idx
    when: hostname == "P2"
