hostname: PE1
interfaces:
 -  name : Loopback0
    address: 1.1.1.1/32
    description: System_Loopback_Interface
 -  name : GigabitEthernet0/0/0/2
    address: 12.0.0.1/24
    description: PE1_to_P2
protocols:
  isis:
   -  net: 49.0000.0000.0001.00
      sid: 1
      interfaces:
        -  name: Loopback0
           loopback: True
        -  name: GigabitEthernet0/0/0/2
           loopback: False
           metric: 10

