---
hostname: PE5
interfaces:
 -  name : Loopback0
    address: 5.5.5.5/32
    description: System_Loopback_Interface
 -  name : GigabitEthernet0/0/0/0
    address: 45.0.0.5/24
    description: PE5_to_P4
protocols:
  isis:
   -  net: 49.0000.0000.0005.00
      sid: 5
      interfaces:
        -  name: Loopback0
           loopback: True
        -  name: GigabitEthernet0/0/0/0
           loopback: False
           metric: 10

